/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package my.slots;

import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class BlackJackUI extends javax.swing.JFrame {

    private int cardsDrawn;
    private int sum;
    private int sumDealer;
    private int einsatz;
    private BlackJack b;
            Dealer d = new Dealer();
    public BlackJackUI() {
        initComponents();
        b = new BlackJack();
        jLabel2.setText(b.getMoney()+"");
        einsatz = Integer.parseInt(JOptionPane.showInputDialog("Einsatz eingeben: "));
        
    }
    public BlackJackUI(int cash){
        initComponents();
        b = new BlackJack(cash);
        jLabel2.setText(cash+"");
                b.addMoney(-einsatz);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Money:");

        jLabel2.setText("jLabel2");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/slots/box.png"))); // NOI18N

        jButton3.setText("Draw");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Stay");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel12.setText("$50 to play!");

        jLabel13.setText("Total:");

        jLabel14.setText("jLabel14");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(jButton3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel5)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel6)
                        .addContainerGap(496, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addComponent(jLabel14))
                        .addGap(146, 146, 146))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13))))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton3))
                .addContainerGap(201, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        
        d.cardDealer();
        JFrame f;  
        f=new JFrame();
        Card it = b.getCard();

        if(it.getNumber()<10&&it.getNumber()>1){
            sum+=it.getNumber();
        }else if(it.getNumber() == 1){
            int a=JOptionPane.showConfirmDialog(f,"Wollen Sie als 1 zählen lassen? (Nein falls sie 11 wollen)");  
                if(a==JOptionPane.YES_OPTION){  
                    sum += 1;
                    f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);  
            }
                else{
            sum+= 11;
                }
        }
        else{
            sum+=10;
        }
        jLabel14.setText(sum+"");
        if(cardsDrawn==0){
            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/slots/pics/"+it.getNumber()+ " " + it.getSuit()+ ".jpg")));
            
        }else if (cardsDrawn==1){
            jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/slots/pics/"+it.getNumber()+ " " + it.getSuit()+ ".jpg")));
        }else if (cardsDrawn==2){
            jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/slots/pics/"+it.getNumber()+ " " + it.getSuit()+ ".jpg")));
        }else if (cardsDrawn==3){
            jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/slots/pics/"+it.getNumber()+ " " + it.getSuit()+ ".jpg")));
        }else{
            return;
        }
        
        cardsDrawn++;
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        cardsDrawn=0;
        b.addMoney(-einsatz);
        int sumDealer = d.getSumDealer();
        JFrame f;  
        f=new JFrame();  
        JOptionPane.showMessageDialog(f,"Dealer hatte " + sumDealer + " Punkte","Auswertung",JOptionPane.WARNING_MESSAGE);     
        if(sumDealer > 21 && sum > 21){
            b.addMoney(einsatz);
        }
        else if(sumDealer == sum){
            b.addMoney(einsatz);
        }
        else if(sumDealer > 21){
            b.addMoney(einsatz*2);
        }
        else if(sum > 21){
            
        }
        else if(sumDealer > sum){
            
        }
        else if(sum > sumDealer){
            b.addMoney(einsatz*2);
        }
        sum = 0;
        d.setSumDealer(0);
        einsatz = 0;
        System.out.println(b.getMoney()+"");
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/slots/box.png")));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/slots/box.png")));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/slots/box.png")));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/slots/box.png")));
        jLabel2.setText(b.getMoney()+"");
        einsatz = Integer.parseInt(JOptionPane.showInputDialog("Einsatz eingeben: "));
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BlackJackUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BlackJackUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BlackJackUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BlackJackUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new BlackJackUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
